### ISSUE TITLE
triger map

### ISSUE THREAD

**Issue by rafmvd** [reepblue/luawerks#1]
Good afternoon. I bought your script, but when creating a trigger for moving to another level, nothing happens. how to make the triger map script work.

**Comment by reepblue** [comment]
Good evening,

Please discribe how you are using it. Maps are loaded just by providing the
map name. There is no prefix or extension. So instead of "Maps/start.map"
you would just supply "start".

I hope this helps.

**Comment by rafmvd** [comment]
Hello . The problem is when I set the squeak trigger TriggerChangeMap.lua does not load the next level.

**Comment by rafmvd** [comment]
write me how to implement the transition to the next level. When the fps player stepped on the trigger.

**Comment by rafmvd** [comment]
https://www.leadwerks.com/learn?page=Tutorials_Games_Marble-Game_Changing-Levels
 do this instruction. but does not transfer to another map.

**Comment by rafmvd** [comment]
--[[
This script will act as a trigger to change the current map.
Place this at the end of your map to make the player progress
to the next level.
]]--

Script.mapname=""--string "Map Name"

function Script:Start()
	self.enabled=true
end

function Script:Collision(entity, position, normal, speed)
	changemapname=self.mapname
end

function Script:Enable()--in
	if self.enabled==false then
		self.enabled=true
		self:CallOutputs("Enable")
	end
end

function Script:Disable()--in
	if self.enabled then
		self.enabled=false
		self:CallOutputs("Disable")
	end
end
this script does not work.

**Comment by rafmvd** [comment]
Thank you large like has understood.it was necessary to import the Trigger Change Map script.lua.

**Comment by reepblue** [comment]
Use LoadMap(self.mapname) instead of changemapname=self.mapname. Don't include directories or extensions.

Source:
https://github.com/reepblue/luawerks/wiki/Setting-Up-Luawerks

**Comment by rafmvd** [comment]
thank you very much, it helped.26.10.2018, 01:52, "Steven" <notifications@github.com>:Use LoadMap(self.mapname) instead of changemapname=self.mapname. Don't include directories or extensions.
Source:
https://github.com/reepblue/luawerks/wiki/Setting-Up-Luawerks
