### ISSUE TITLE
button.lua throws a error in the current beta of Leadwerks

### ISSUE THREAD

**Issue by karmacomposer** [reepblue/luawerks#3]
This code throws an error in button.lua:

[function Script.And(set, flag)
    return set % (2*flag) >= flag
end](url)

Here is the error:

["C:/Users/spong/Documents/Leadwerks/Projects/Gobie/Scripts/GUI/Button.lua" : 233 : attempt to perform arithmetic on local 'set' (a string value)](url)

Please fix.

Thank you.

**Comment by karmacomposer** [comment]
I commented out the middle line and Leadwerks runs - not sure what that does to the function though?

Mike

**Comment by reepblue** [comment]
This is fixed for the next release. SetStyle has been changed in Leadwerks 4.6
